name: Build Server A

on:
  workflow_call: 
    inputs:
      tag:
        required: true
        type: string

jobs:

  build:
    name: Build Server A
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Pushing the new tag
        env:
            REPOA_PAT: ${{ secrets.REPOA_PAT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ inputs.tag }}
          git push https://x-access-token:${REPOA_PAT}@github.com/wporta/serverA.git --tags

      - name: Building
        run: |
          echo "Building Server A for tag: ${{ inputs.tag }}"
          sleep 2m
          echo "Done building"