name: Server A

on:
  push: 
    tags:
      - 'v\d+(\.\d+){1,2}(\.\d+)?'
      #- 'v*'
    
jobs:
  build:
    name: Building with tag push
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ github.ref_name }}