name: Server A

on:
  push: 
    tags:
      - 'v\d+(\.\d+){2,3}'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "Building Server A for tag: ${{ github.ref_name }}"